# Generated by Django 5.1.4 on 2025-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите дополнительное описание",
                null=True,
                verbose_name="описание",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите ваше имя",
                max_length=150,
                null=True,
                verbose_name="имя пользователя",
            ),
        ),
    ]
