# Generated by Django 5.1.4 on 2025-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_description_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите дополнительное описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Введите ваше имя",
                max_length=50,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Введите вашу фамилию", max_length=50, verbose_name="Фамилия"
            ),
        ),
    ]
