# Generated by Django 5.1.4 on 2025-01-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_name_alter_user_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                max_length=35,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
