# Generated by Django 5.1.4 on 2025-01-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_paid_it_payment_paid_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите информацию о себе",
                null=True,
                verbose_name="О себе",
            ),
        ),
    ]
