# Generated by Django 5.1.4 on 2025-01-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_is_subscribed_alter_payment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_publisher",
            field=models.BooleanField(
                default=False, verbose_name="Пользователь является автором"
            ),
        ),
    ]
