# Generated by Django 5.1.4 on 2025-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_verification",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="код верификации"
            ),
        ),
    ]
