# Generated by Django 5.1.4 on 2025-01-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="name",
            new_name="nickname",
        ),
    ]
