# Generated by Django 5.1.4 on 2025-01-04 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0002_rename_name_publisher_nickname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "Публикация", "verbose_name_plural": "Публикации"},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"verbose_name": "Издатель", "verbose_name_plural": "Издатели"},
        ),
        migrations.AddField(
            model_name="content",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Укажите описание публикации",
                null=True,
                verbose_name="Описание публикации",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора публикации",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profitpages.publisher",
                verbose_name="Автор публикации",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Введите название публикации",
                max_length=150,
                null=True,
                verbose_name="Название публикации",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание автора",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите имя пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Введите псевдоним автора",
                max_length=150,
                null=True,
                verbose_name="Псевдоним",
            ),
        ),
    ]
