# Generated by Django 5.1.4 on 2025-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0003_alter_content_options_alter_publisher_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="paid",
            field=models.BooleanField(default=False, help_text="Платный"),
        ),
    ]
