# Generated by Django 5.1.4 on 2025-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0004_content_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="paid",
            field=models.BooleanField(
                default=False,
                help_text="Укажите тип контента:(Платный/Бесплатный)",
                verbose_name="Платный",
            ),
        ),
    ]
