# Generated by Django 5.1.4 on 2025-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0005_alter_content_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью публикации",
                null=True,
                upload_to="content/preview",
                verbose_name="Превью",
            ),
        ),
    ]
