# Generated by Django 5.1.4 on 2025-01-11 18:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0007_alter_content_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="содержание публикации"
            ),
        ),
    ]
