# Generated by Django 5.1.4 on 2025-01-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0008_content_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="дата последнего изменения"
            ),
        ),
    ]
