# Generated by Django 5.1.4 on 2025-01-14 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0010_rename_content_publication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора публикации",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication",
                to="profitpages.publisher",
                verbose_name="Автор публикации",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя, который является владельцем издательства",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Активна ли подписка"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Время обновления подписки",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подписка активна до"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
