# Generated by Django 5.1.4 on 2025-01-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profitpages",
            "0011_alter_publication_publisher_alter_publisher_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="link",
            field=models.TextField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="ссылка на видео",
            ),
        ),
    ]
