# Generated by Django 5.1.4 on 2025-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profitpages", "0012_publication_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Укажите ссылку на видео",
                max_length=150,
                null=True,
                verbose_name="ссылка на видео",
            ),
        ),
    ]
